# Generated by Django 4.0.5 on 2022-07-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_categoryimage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='photo/category/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
