# Generated by Django 4.0.5 on 2022-07-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_category_image_delete_categoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='photo/product/%Y/%m/%d/'),
        ),
    ]
