# Generated by Django 4.0.5 on 2022-07-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
